# Intro to Numpy

In [1]:
import numpy as np

In [2]:
mylist=[12,32,4,51,11]
arr=np.array(mylist)

In [3]:
arr

array([12, 32,  4, 51, 11])

In [4]:
arr.shape

(5,)

In [5]:
mylist=[[[12,32],[4,51],[11,3]]]
arr=np.array(mylist,np.int32)


In [6]:
arr.dtype

dtype('int32')

In [7]:
arr.shape

(1, 3, 2)

In [8]:
arr

array([[[12, 32],
        [ 4, 51],
        [11,  3]]])

In [9]:
arr.ndim #dimension

3

In [10]:
type(arr)

numpy.ndarray

**ndarray is a class and arr is an object of class. 
arr.min(),arr.mean() etc functions can be called using obj arr**

* Intrinsic numpy creation objects(arange,ones,zeros) `

In [11]:
zero=np.zeros((2,3))

In [12]:
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
zero.dtype

dtype('float64')

In [51]:
zero=np.zeros((2,3),dtype='int') #defininig type
zero

array([[0, 0, 0],
       [0, 0, 0]])

In [15]:
 rng=np.arange(6)

In [16]:
rng

array([0, 1, 2, 3, 4, 5])

In [17]:
rng=np.arange(0,5,2) #can produce floating values as well

In [18]:
rng

array([0, 2, 4])

In [19]:
r=range(5)

In [20]:
r

range(0, 5)

In [21]:
listobj=list(r)

In [22]:
listobj

[0, 1, 2, 3, 4]

In [23]:
 l=np.linspace(1,4,3) #betwn 1 nd 4, gives 3 equally spaced element

In [24]:
l

array([1. , 2.5, 4. ])

In [49]:
ide=np.identity(4,dtype='int')# identity matrix of order 4

In [50]:
ide

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [27]:
arr=np.arange(99)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [30]:
arr=arr.reshape(3,33)

<h1> arr gets updated. resize directly updates the original arry when called by arr.resize() unlike reshape where it has to be updated 

In [31]:
a=np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [32]:
arr=arr.ravel()# changes to initial format

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [34]:
x=[[1,5],[2,4],[5,9]]

In [35]:
ar=np.array(x)

In [36]:
ar.sum(axis=0)

array([ 8, 18])

In [37]:
ar.sum(axis=1)

array([ 6,  6, 14])

In [38]:
ar.T

array([[1, 2, 5],
       [5, 4, 9]])

In [39]:
for i in ar.flat:
    print(i)

1
5
2
4
5
9


In [40]:
ar

array([[1, 5],
       [2, 4],
       [5, 9]])

In [41]:
ar.flat

In [42]:
ar

array([[1, 5],
       [2, 4],
       [5, 9]])

In [43]:
a1=np.array([12,34,55,78,9])

In [44]:
a1.argmax()

3

In [45]:
a1.argmin()

4

In [46]:
a1.argsort()

array([4, 0, 1, 2, 3], dtype=int64)

In [47]:
np.where(ar>2)

(array([0, 1, 2, 2], dtype=int64), array([1, 1, 0, 1], dtype=int64))