# Vectorization,Mean,Medain,Variance,Std Deviation,Percentile,Quartile

In [1]:
import numpy as np

In [2]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#adding 10 to each element in list
newlist=[]
for i in arr:
    newlist.append(i+10)
arr1=np.array(newlist)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr1=arr+10 #precised work using numpy array
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
arr2=np.arange(10,20)
if arr1.shape==arr2.shape:
    a=arr1+arr2
a

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [15]:
#realtime execution, time management
arr1.resize(5,2)
arr2.resize(5,2)
a=arr1+arr2
a

array([[20, 22],
       [24, 26],
       [28, 30],
       [32, 34],
       [36, 38]])

In [17]:
age=np.array([10,22,20,35,43,19])
arb=np.array([True,False,True,False,True,False])
age[arb] #true values are returned. A Boolean array can be used as a filter 

array([10, 20, 43])

In [20]:
age[age<20] #to find teenagers

array([10, 19])

In [22]:
#age less than 20 more than 40
age[(age<20) | (age>40)] #or gate , it is not logical or

array([10, 43, 19])

In [24]:
#age btwn 20 and 40
age[(age>20) & (age<40)] 

array([22, 35])

In [25]:
#age that are not less than 20 -> compliment
age[~(age>20)] 

array([10, 20, 19])

In [31]:
sal=np.array([20000,22000,30000,25000,21000])
sal.mean() #sal is ndarray object

23600.0

In [32]:
np.mean(sal)

23600.0

In [47]:
sal=np.array([20000,22000,30000,25000,21000])
sal.mean() #mean fails to give a right answer,70k is a higher than avg , we use median

23600.0

s=np.sort(sal)#median needs sorting

np.median(s)#mid value

In [48]:
np.median(sal)#call through numpy module,object call not available

22000.0

err=sal-22000
err

err**2 #squared to remove sign and prevent error becoming 0

np.round(np.mean(err**2),2) #variance is the mean of squared error

In [52]:
np.var(sal)

13040000.0

In [53]:
np.sqrt(np.var(sal)) #standard deviation -> measure of error for the mean not median

3611.0940170535578

In [55]:
np.std(sal) #direct function

3611.0940170535578

In [56]:
np.quantile(sal,q=.8) #80th percentile

26000.0

In [57]:
np.quantile(sal,q=.5) #50th percentile ->median

22000.0