# Random submodule

In [1]:
import numpy as np

In [2]:
#generating random value
arr=np.random.rand(10) #random is submodule of numpy, values 0<=n<1
arr

array([0.03725483, 0.35187201, 0.64552256, 0.23424079, 0.49047339,
       0.8532368 , 0.35045633, 0.91326174, 0.24330097, 0.99621861])

In [3]:
arr=np.random.rand(3,2) #2d
arr

array([[0.52503136, 0.13208332],
       [0.76853543, 0.00415016],
       [0.10665084, 0.97353784]])

random number keeps changing every time it is run. needs to be fixed

In [4]:
#seed function to be used in same cell
np.random.seed(10) #any integer can be passed,same value in seed gives same data set
arr=np.random.rand(3,2)
arr

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665]])

In [5]:
arr=np.random.normal(loc=50,scale=1,size=10) #10 picked number from a normal distribution(bell curve) with mean 50 and sd 1
arr

array([50.62133597, 49.27991444, 50.26551159, 50.10854853, 50.00429143,
       49.82539979, 50.43302619, 51.20303737, 49.03493433, 51.02827408])

In [6]:
arr=np.random.normal(loc=50,scale=1,size=(3,2)) #2d
arr

array([[50.22863013, 50.44513761],
       [48.86339779, 50.13513688],
       [51.484537  , 48.92019511]])

In [7]:
#to simulate errors
arr=np.random.randn(5) #5 normal distribution values, mean is 0, sd 1
arr

array([-1.97772828, -1.7433723 ,  0.26607016,  2.38496733,  1.12369125])

Any normal distribution with mean 0,sd 1 -> standard normal distribution

In [8]:
arr=np.random.randint(low=10,high=17,size=10) #10<=n<17
arr

array([16, 10, 13, 14, 12, 10, 11, 12, 10, 16])

In [9]:
v1=np.array([10,10,10]) 
v2=np.array([5,5,5])
np.dot(v1,v2) #vector dot product

150

In [10]:
arr1=np.random.randint(2,7,(3,2))
arr2=np.random.randint(2,7,(2,4)) #compatible for multiplication
np.dot(arr1,arr2) #3X4 matrix

array([[42, 38, 14, 14],
       [48, 42, 16, 16],
       [54, 42, 18, 18]])

In [11]:
arr1=np.random.randint(2,7,(3,3))
np.linalg.det(arr1) #linalg->linear algebra submodule

40.000000000000014

In [12]:
# new array with t for age<20 , nt for age>20
age=np.array([10,22,20,35,43,19]) 
np.where(age<20,'T','F') #ternary operator function

array(['T', 'F', 'F', 'F', 'F', 'T'], dtype='<U1')

 U is string datatype

In [13]:
arr=np.array([1,2.4,3,4],dtype="str") #explicit type cast
arr

array(['1', '2.4', '3', '4'], dtype='<U3')

<h1> Pandas

In [14]:
import numpy as np
import pandas as pd

In [15]:
marks=[90,78,89,71]
names=['john','tom','robert','harry']

* Series is a class of panda

In [26]:
ser=pd.Series(marks,index=names) #(values,index) , key value pair like dictionary
ser

john      90
tom       78
robert    89
harry     71
dtype: int64

In [17]:
ser['john']

90

In [18]:
ser['john']=99
ser

john      99
tom       78
robert    89
harry     71
dtype: int64

In [19]:
ser['alice']=89 #entering new key
ser

john      99
tom       78
robert    89
harry     71
alice     89
dtype: int64

In [20]:
del ser['robert'] #del to delete
ser

john     99
tom      78
harry    71
alice    89
dtype: int64

In [21]:
for i in ser:
    print(i) 

99
78
71
89


In dictionaries the keys are printed if loop is used, here values are printed

In [22]:
#checking if key exists or not
'virat' in ser

False

In [23]:
'harry' in ser

True

In [24]:
ser=pd.Series(marks) #index is not compulsory,but in dictionaries key has to be given
ser

0    90
1    78
2    89
3    71
dtype: int64

In [27]:
#reordering entries
ser=pd.Series(marks,index=names)
ser.reindex(['harry','alice','john','tom','robert'])
ser

john      90
tom       78
robert    89
harry     71
dtype: int64

In [29]:
ser=ser.reindex(['harry','alice','john','tom','robert','david'])
ser

harry     71.0
alice      NaN
john      90.0
tom       78.0
robert    89.0
david      NaN
dtype: float64

NaN stands for not a number-> a float value type, signifies missing value

In [32]:
ser['david']=92
ser['alice']=97
ser

harry     71.0
alice     97.0
john      90.0
tom       78.0
robert    89.0
david     92.0
dtype: float64

In [33]:
ser+2

harry     73.0
alice     99.0
john      92.0
tom       80.0
robert    91.0
david     94.0
dtype: float64

In [34]:
ser[ser<90]

harry     71.0
tom       78.0
robert    89.0
dtype: float64

In [35]:
type(ser)

pandas.core.series.Series

In [41]:
arr=ser.values
 #changed to numpy array
arr

array([71., 97., 90., 78., 89., 92.])

In [43]:
arr=arr.astype('int')#changing type
arr

array([71, 97, 90, 78, 89, 92])

In [37]:
arr1=ser.index.values
arr1

array(['harry', 'alice', 'john', 'tom', 'robert', 'david'], dtype=object)